/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdultoRouteImport } from './routes/adulto'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisionLunesRouteImport } from './routes/mision.lunes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultoRoute = AdultoRouteImport.update({
  id: '/adulto',
  path: '/adulto',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisionLunesRoute = MisionLunesRouteImport.update({
  id: '/mision/lunes',
  path: '/mision/lunes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adulto': typeof AdultoRoute
  '/perfil': typeof PerfilRoute
  '/mision/lunes': typeof MisionLunesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adulto': typeof AdultoRoute
  '/perfil': typeof PerfilRoute
  '/mision/lunes': typeof MisionLunesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adulto': typeof AdultoRoute
  '/perfil': typeof PerfilRoute
  '/mision/lunes': typeof MisionLunesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adulto' | '/perfil' | '/mision/lunes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adulto' | '/perfil' | '/mision/lunes'
  id: '__root__' | '/' | '/adulto' | '/perfil' | '/mision/lunes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdultoRoute: typeof AdultoRoute
  PerfilRoute: typeof PerfilRoute
  MisionLunesRoute: typeof MisionLunesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adulto': {
      id: '/adulto'
      path: '/adulto'
      fullPath: '/adulto'
      preLoaderRoute: typeof AdultoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mision/lunes': {
      id: '/mision/lunes'
      path: '/mision/lunes'
      fullPath: '/mision/lunes'
      preLoaderRoute: typeof MisionLunesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdultoRoute: AdultoRoute,
  PerfilRoute: PerfilRoute,
  MisionLunesRoute: MisionLunesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
